// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { LinkProps } from 'next/link';
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'pl';

export type Locales = 'en' | 'pl';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  MENU: {
    JOIN_US: string;
    CONFIGURATOR: string;
    LINK: string;
    FALLBACK: string;
    PRIVACY_POLICY: string;
  };
  HOURS: {
    MON_FRI: string;
    SAT: string;
  };
  COMMON: {
    WRITE_A_MESSAGE: string;
    EMAIL: string;
    ADDRESS: string;
    OPEN_HOURS: string;
  };
  VALIDATION: {
    PASSWORD_MUST_CONTAIN: string;
  };
  ERROR: {
    NOT_FOUND_TITLE: string;
    NOT_FOUND_DESCRIPTION: string;
    NOT_FOUND_BUTTON: string;
  };
  CREDITS: {
    AUTHOR: string;
  };
  SEO: {
    LOGIN_ARIA_LABEL: string;
  };
};

export type TranslationFunctions = {
  MENU: {
    JOIN_US: () => LocalizedString;
    CONFIGURATOR: () => LocalizedString;
    LINK: (arg: LinkProps['href']) => LocalizedString;
    FALLBACK: () => LocalizedString;
    PRIVACY_POLICY: () => LocalizedString;
  };
  HOURS: {
    MON_FRI: () => LocalizedString;
    SAT: () => LocalizedString;
  };
  COMMON: {
    WRITE_A_MESSAGE: () => LocalizedString;
    EMAIL: () => LocalizedString;
    ADDRESS: () => LocalizedString;
    OPEN_HOURS: () => LocalizedString;
  };
  VALIDATION: {
    PASSWORD_MUST_CONTAIN: () => LocalizedString;
  };
  CREDITS: {
    AUTHOR: () => LocalizedString;
  };
  ERROR: {
    NOT_FOUND_TITLE: () => LocalizedString;
    NOT_FOUND_DESCRIPTION: () => LocalizedString;
    NOT_FOUND_BUTTON: () => LocalizedString;
  };
  SEO: {
    LOGIN_ARIA_LABEL: () => LocalizedString;
  };
};

export type Formatters = {};
