// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { LinkProps } from 'next/link';
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'pl';

export type Locales = 'en' | 'pl';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  MENU: {
    JOIN_US: string;
    CONFIGURATOR: string;
    LINK: string;
    FALLBACK: string;
  };
  HOURS: {
    MON_FRI: string;
    SAT: string;
  };
  COMMON: {
    WRITE_A_MESSAGE: string;
  };
};

export type TranslationFunctions = {
  MENU: {
    JOIN_US: () => LocalizedString;
    CONFIGURATOR: () => LocalizedString;
    LINK: (arg: LinkProps['href']) => LocalizedString;
    FALLBACK: () => LocalizedString;
  };
  HOURS: {
    MON_FRI: () => LocalizedString;
    SAT: () => LocalizedString;
  };
  COMMON: {
    WRITE_A_MESSAGE: () => LocalizedString;
  };
};

export type Formatters = {};
