// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { LinkProps } from 'next/link';
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'pl';

export type Locales = 'en' | 'pl';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  MENU: {
    JOIN_US: string;
    CONFIGURATOR: string;
    LINK: string;
    FALLBACK: string;
    PRIVACY_POLICY: string;
  };
  HOURS: {
    MON_FRI: string;
    SAT: string;
  };
  COMMON: {
    WRITE_A_MESSAGE: string;
    EMAIL: string;
    ADDRESS: string;
    OPEN_HOURS: string;
  };
  ERROR: {
    NOT_FOUND_TITLE: string;
    NOT_FOUND_DESCRIPTION: string;
    NOT_FOUND_BUTTON: string;
  };
  CREDITS: {
    AUTHOR: string;
  };
  SEO: {
    LOGIN_ARIA_LABEL: string;
  };
  LOGIN: {
    TITLE: string;
    FORGET_PASSWORD: string;
    REGISTER: string;
    SUBMIT_BUTTON: string;
    OR: string;
    SIGN_IN_WITH_GOOGLE: string;
    SIGN_IN_WITH_GITHUB: string;
    PASSWORD: string;
  };
  VALIDATION: {
    /**
     * @param {string} field
     */
    REQUIRED: RequiredParams<string>;
    EMAIL_IS_TAKEN: string;
    INCORRECT_PASSWORD_OR_LOGIN: string;
  };
};

export type TranslationFunctions = {
  MENU: {
    JOIN_US: () => LocalizedString;
    CONFIGURATOR: () => LocalizedString;
    LINK: (arg: LinkProps['href']) => LocalizedString;
    FALLBACK: () => LocalizedString;
    PRIVACY_POLICY: () => LocalizedString;
  };
  HOURS: {
    MON_FRI: () => LocalizedString;
    SAT: () => LocalizedString;
  };
  COMMON: {
    WRITE_A_MESSAGE: () => LocalizedString;
    EMAIL: () => LocalizedString;
    ADDRESS: () => LocalizedString;
    OPEN_HOURS: () => LocalizedString;
  };
  CREDITS: {
    AUTHOR: () => LocalizedString;
  };
  ERROR: {
    NOT_FOUND_TITLE: () => LocalizedString;
    NOT_FOUND_DESCRIPTION: () => LocalizedString;
    NOT_FOUND_BUTTON: () => LocalizedString;
  };
  SEO: {
    LOGIN_ARIA_LABEL: () => LocalizedString;
  };
  LOGIN: {
    TITLE: () => LocalizedString;
    FORGET_PASSWORD: () => LocalizedString;
    REGISTER: () => LocalizedString;
    SUBMIT_BUTTON: () => LocalizedString;
    OR: () => LocalizedString;
    SIGN_IN_WITH_GOOGLE: () => LocalizedString;
    SIGN_IN_WITH_GITHUB: () => LocalizedString;
    PASSWORD: () => LocalizedString;
  };
  VALIDATION: {
    REQUIRED: (arg: { field: string }) => LocalizedString;
    EMAIL_IS_TAKEN: () => LocalizedString;
    INCORRECT_PASSWORD_OR_LOGIN: () => LocalizedString;
  };
};

export type Formatters = {};
