export * from './confirmEmail.validator';
export * from './email.validator';
export * from './firstName.validator';
export * from './isOrderPlaced.validator';
export * from './lastName.validator';
export * from './order-id.validator';
export * from './phone-validators-deprecated';
export * from './phone-validators';
export * from './taxId.validator';
